### PR TITLE
Valid IP Address

### PR DESCRIPTION
**Pull request by ayesha-2101**

### CODE REVIEW

**Comment by ayesha-2101** [comment]
@Jagroop2001 it is done and pull request has been raised

**Comment by jagroop-dev-11** [comment]
@ayesha-2101 , please resolve merge conflicts.

**Comment by jagroop-dev-11** [comment]
@ayesha-2101 , I have resolved the conflicts . Please add this utility function in the readme.md file

**Comment by jagroop-dev-11** [comment]
@ayesha-2101 , you are just one step closed for acceptance of this issue. If I didn't get any response  then I have to assign this to someone else.

**Comment by ayesha-2101** [comment]
sure I will do it in a while @Jagroop2001

**Comment by jagroop-dev-11** [comment]
https://github.com/Jagroop2001/validify-string/issues/6

**Pull request merged**
