### PR TITLE
added ishash, isalphanumeric, ishexadecimal fn

### PR DESCRIPTION
**Pull request by debuuuu007**

### CODE REVIEW

**Comment by debuuuu007** [comment]
You can add this as it resolves a issue of yours.

**Comment by jagroop-dev-11** [comment]
@debuuuu007 , please add these in `readme.md` file within same PR. After that it's ready to merge.

**Comment by debuuuu007** [comment]
I have updated the readme you can check it out.

**Comment by jagroop-dev-11** [comment]
https://github.com/Jagroop2001/validify-string/issues/17

**Pull request merged**
